services:
  mysql:
    container_name: 'typeorm-issue-6908-mysql'
    image: mysql:8.0.21
    restart: always
    environment:
      MYSQL_DATABASE: typeorm-issue-6908-mysql
      MYSQL_USER: developer
      MYSQL_PASSWORD: repoleved
      MYSQL_ROOT_PASSWORD: toor
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    networks:
      - typeorm-issue-6908-mysql
    volumes:
      - typeorm-issue-6908-mysql-volume:/var/lib/mysql
networks:
  typeorm-issue-6908-mysql:
    name: typeorm-issue-6908-mysql
volumes:
  typeorm-issue-6908-mysql-volume:
    name: typeorm-issue-6908-mysql
